project_id = "reviewping"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enable_signup = true
enable_confirmations = false

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 8083
deno_version = 2

[analytics]
enabled = true
port = 54327
backend = "postgres"
