-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================
-- PROFILES (extends auth.users)
-- ============================
CREATE TABLE "profiles" (
  "id"         UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  "email"      TEXT,
  "name"       TEXT,
  "business_name" TEXT,
  "plan"       TEXT DEFAULT 'growth',
  "created_at" TIMESTAMPTZ DEFAULT now()
);

-- ============================
-- REVIEWS
-- ============================
CREATE TABLE "reviews" (
  "id"        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"   UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "name"      TEXT NOT NULL,
  "service"   TEXT,
  "rating"    INT CHECK (rating >= 1 AND rating <= 5),
  "text"      TEXT,
  "status"    TEXT DEFAULT 'pending',
  "channel"   TEXT,
  "sentAt"    TIMESTAMPTZ DEFAULT now(),
  "reply"     TEXT
);

-- ============================
-- CONTACTS
-- ============================
CREATE TABLE "contacts" (
  "id"        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"   UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "name"      TEXT NOT NULL,
  "phone"     TEXT,
  "email"     TEXT,
  "service"   TEXT,
  "visits"    INT DEFAULT 1,
  "optedOut"  BOOLEAN DEFAULT false,
  "lastSent"  TIMESTAMPTZ
);

-- ============================
-- TEMPLATES
-- ============================
CREATE TABLE "templates" (
  "id"      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "name"    TEXT NOT NULL,
  "text"    TEXT NOT NULL,
  "service" TEXT DEFAULT 'All'
);

-- ============================
-- BUSINESS SETTINGS
-- ============================
CREATE TABLE "business_settings" (
  "user_id"       UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  "business_name" TEXT,
  "biz_type"      TEXT,
  "google_link"   TEXT,
  "updated_at"    TIMESTAMPTZ DEFAULT now()
);

-- ============================
-- NOTIFICATIONS
-- ============================
CREATE TABLE "notifications" (
  "id"      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "type"    TEXT,
  "title"   TEXT,
  "body"    TEXT,
  "time"    TIMESTAMPTZ DEFAULT now(),
  "read"    BOOLEAN DEFAULT false,
  "icon"    TEXT
);

-- ============================
-- TEAM MEMBERS
-- ============================
CREATE TABLE "team_members" (
  "id"       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"  UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "name"     TEXT,
  "email"    TEXT,
  "role"     TEXT DEFAULT 'Staff',
  "status"   TEXT DEFAULT 'active',
  "joinedAt" TIMESTAMPTZ DEFAULT now()
);

-- ============================
-- SUBSCRIPTIONS (Stripe)
-- ============================
CREATE TABLE "subscriptions" (
  "id"                     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"                UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "stripe_customer_id"     TEXT,
  "stripe_subscription_id" TEXT,
  "plan_id"                TEXT,
  "status"                 TEXT DEFAULT 'active',
  "current_period_start"   TIMESTAMPTZ,
  "current_period_end"     TIMESTAMPTZ,
  "created_at"             TIMESTAMPTZ DEFAULT now()
);

-- ============================
-- ROW LEVEL SECURITY
-- ============================
ALTER TABLE "profiles"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reviews"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "contacts"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "templates"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "business_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE "team_members"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "subscriptions"    ENABLE ROW LEVEL SECURITY;

-- ============================
-- RLS POLICIES — Profiles
-- ============================
CREATE POLICY "profiles_own_select" ON "profiles"
  FOR SELECT USING (id = auth.uid());
CREATE POLICY "profiles_own_insert" ON "profiles"
  FOR INSERT WITH CHECK (id = auth.uid());
CREATE POLICY "profiles_own_update" ON "profiles"
  FOR UPDATE USING (id = auth.uid());

-- ============================
-- RLS POLICIES — Reviews
-- ============================
CREATE POLICY "reviews_own_select" ON "reviews"
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "reviews_own_insert" ON "reviews"
  FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "reviews_own_update" ON "reviews"
  FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "reviews_own_delete" ON "reviews"
  FOR DELETE USING (user_id = auth.uid());

-- ============================
-- RLS POLICIES — Contacts
-- ============================
CREATE POLICY "contacts_own_select" ON "contacts"
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "contacts_own_insert" ON "contacts"
  FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "contacts_own_update" ON "contacts"
  FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "contacts_own_delete" ON "contacts"
  FOR DELETE USING (user_id = auth.uid());

-- ============================
-- RLS POLICIES — Templates
-- ============================
CREATE POLICY "templates_own_select" ON "templates"
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "templates_own_insert" ON "templates"
  FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "templates_own_update" ON "templates"
  FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "templates_own_delete" ON "templates"
  FOR DELETE USING (user_id = auth.uid());

-- ============================
-- RLS POLICIES — Business Settings
-- ============================
CREATE POLICY "business_settings_own_select" ON "business_settings"
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "business_settings_own_insert" ON "business_settings"
  FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "business_settings_own_update" ON "business_settings"
  FOR UPDATE USING (user_id = auth.uid());

-- ============================
-- RLS POLICIES — Notifications
-- ============================
CREATE POLICY "notifications_own_select" ON "notifications"
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "notifications_own_insert" ON "notifications"
  FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "notifications_own_update" ON "notifications"
  FOR UPDATE USING (user_id = auth.uid());

-- ============================
-- RLS POLICIES — Team Members
-- ============================
CREATE POLICY "team_own_select" ON "team_members"
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "team_own_insert" ON "team_members"
  FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "team_own_update" ON "team_members"
  FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "team_own_delete" ON "team_members"
  FOR DELETE USING (user_id = auth.uid());

-- ============================
-- RLS POLICIES — Subscriptions
-- ============================
CREATE POLICY "subscriptions_own_select" ON "subscriptions"
  FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "subscriptions_own_insert" ON "subscriptions"
  FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "subscriptions_own_update" ON "subscriptions"
  FOR UPDATE USING (user_id = auth.uid());

-- ============================
-- INDEXES for performance
-- ============================
CREATE INDEX idx_reviews_user_id     ON "reviews" ("user_id");
CREATE INDEX idx_reviews_status      ON "reviews" ("status");
CREATE INDEX idx_contacts_user_id    ON "contacts" ("user_id");
CREATE INDEX idx_contacts_phone      ON "contacts" ("phone");
CREATE INDEX idx_contacts_email      ON "contacts" ("email");
CREATE INDEX idx_templates_user_id   ON "templates" ("user_id");
CREATE INDEX idx_notifications_user_id ON "notifications" ("user_id");
CREATE INDEX idx_notifications_read  ON "notifications" ("user_id", "read");
CREATE INDEX idx_team_members_user_id ON "team_members" ("user_id");
CREATE INDEX idx_subscriptions_user_id ON "subscriptions" ("user_id");
CREATE INDEX idx_subscriptions_stripe ON "subscriptions" ("stripe_subscription_id");
