-- ============================
-- Migration 005: Complete schema — idempotent & runnable in SQL editor
-- Run this in Supabase Dashboard → SQL Editor if tables are missing
-- ============================

-- 1. PROFILES
CREATE TABLE IF NOT EXISTS "profiles" (
  "id"            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  "email"         TEXT,
  "name"          TEXT,
  "business_name" TEXT,
  "plan"          TEXT DEFAULT 'growth',
  "created_at"    TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_own_select" ON "profiles";
DROP POLICY IF EXISTS "profiles_own_insert" ON "profiles";
DROP POLICY IF EXISTS "profiles_own_update" ON "profiles";
CREATE POLICY "profiles_own_select" ON "profiles" FOR SELECT USING (id = auth.uid());
CREATE POLICY "profiles_own_insert" ON "profiles" FOR INSERT WITH CHECK (id = auth.uid());
CREATE POLICY "profiles_own_update" ON "profiles" FOR UPDATE USING (id = auth.uid()) WITH CHECK (id = auth.uid() AND plan = (SELECT plan FROM "profiles" WHERE id = auth.uid()));

-- 2. REVIEWS
CREATE TABLE IF NOT EXISTS "reviews" (
  "id"        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"   UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "name"      TEXT NOT NULL,
  "service"   TEXT,
  "rating"    INT CHECK (rating >= 1 AND rating <= 5),
  "text"      TEXT,
  "status"    TEXT DEFAULT 'pending',
  "channel"   TEXT,
  "sentAt"    TIMESTAMPTZ DEFAULT now(),
  "reply"     TEXT
);
ALTER TABLE "reviews" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reviews_own_select" ON "reviews";
DROP POLICY IF EXISTS "reviews_own_insert" ON "reviews";
DROP POLICY IF EXISTS "reviews_own_update" ON "reviews";
DROP POLICY IF EXISTS "reviews_own_delete" ON "reviews";
CREATE POLICY "reviews_own_select" ON "reviews" FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "reviews_own_insert" ON "reviews" FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "reviews_own_update" ON "reviews" FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "reviews_own_delete" ON "reviews" FOR DELETE USING (user_id = auth.uid());

-- 3. CONTACTS
CREATE TABLE IF NOT EXISTS "contacts" (
  "id"        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"   UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "name"      TEXT NOT NULL,
  "phone"     TEXT,
  "email"     TEXT,
  "service"   TEXT,
  "visits"    INT DEFAULT 1,
  "optedOut"  BOOLEAN DEFAULT false,
  "lastSent"  TIMESTAMPTZ
);
ALTER TABLE "contacts" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "contacts_own_select" ON "contacts";
DROP POLICY IF EXISTS "contacts_own_insert" ON "contacts";
DROP POLICY IF EXISTS "contacts_own_update" ON "contacts";
DROP POLICY IF EXISTS "contacts_own_delete" ON "contacts";
CREATE POLICY "contacts_own_select" ON "contacts" FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "contacts_own_insert" ON "contacts" FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "contacts_own_update" ON "contacts" FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "contacts_own_delete" ON "contacts" FOR DELETE USING (user_id = auth.uid());

-- 4. TEMPLATES
CREATE TABLE IF NOT EXISTS "templates" (
  "id"      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "name"    TEXT NOT NULL,
  "text"    TEXT NOT NULL,
  "service" TEXT DEFAULT 'All'
);
ALTER TABLE "templates" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "templates_own_select" ON "templates";
DROP POLICY IF EXISTS "templates_own_insert" ON "templates";
DROP POLICY IF EXISTS "templates_own_update" ON "templates";
DROP POLICY IF EXISTS "templates_own_delete" ON "templates";
CREATE POLICY "templates_own_select" ON "templates" FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "templates_own_insert" ON "templates" FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "templates_own_update" ON "templates" FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "templates_own_delete" ON "templates" FOR DELETE USING (user_id = auth.uid());

-- 5. BUSINESS_SETTINGS
CREATE TABLE IF NOT EXISTS "business_settings" (
  "user_id"       UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  "business_name" TEXT,
  "biz_type"      TEXT,
  "google_link"   TEXT,
  "updated_at"    TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE "business_settings" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "business_settings_own_select" ON "business_settings";
DROP POLICY IF EXISTS "business_settings_own_insert" ON "business_settings";
DROP POLICY IF EXISTS "business_settings_own_update" ON "business_settings";
CREATE POLICY "business_settings_own_select" ON "business_settings" FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "business_settings_own_insert" ON "business_settings" FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "business_settings_own_update" ON "business_settings" FOR UPDATE USING (user_id = auth.uid());

-- 6. NOTIFICATIONS
CREATE TABLE IF NOT EXISTS "notifications" (
  "id"      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "type"    TEXT,
  "title"   TEXT,
  "body"    TEXT,
  "time"    TIMESTAMPTZ DEFAULT now(),
  "read"    BOOLEAN DEFAULT false,
  "icon"    TEXT
);
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notifications_own_select" ON "notifications";
DROP POLICY IF EXISTS "notifications_own_insert" ON "notifications";
DROP POLICY IF EXISTS "notifications_own_update" ON "notifications";
DROP POLICY IF EXISTS "notifications_own_delete" ON "notifications";
CREATE POLICY "notifications_own_select" ON "notifications" FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "notifications_own_insert" ON "notifications" FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "notifications_own_update" ON "notifications" FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "notifications_own_delete" ON "notifications" FOR DELETE USING (user_id = auth.uid());

-- 7. TEAM_MEMBERS
CREATE TABLE IF NOT EXISTS "team_members" (
  "id"       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"  UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "name"     TEXT,
  "email"    TEXT,
  "role"     TEXT DEFAULT 'Staff',
  "status"   TEXT DEFAULT 'active',
  "joinedAt" TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE "team_members" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "team_own_select" ON "team_members";
DROP POLICY IF EXISTS "team_own_insert" ON "team_members";
DROP POLICY IF EXISTS "team_own_update" ON "team_members";
DROP POLICY IF EXISTS "team_own_delete" ON "team_members";
CREATE POLICY "team_own_select" ON "team_members" FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "team_own_insert" ON "team_members" FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "team_own_update" ON "team_members" FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "team_own_delete" ON "team_members" FOR DELETE USING (user_id = auth.uid());

-- 8. SUBSCRIPTIONS
CREATE TABLE IF NOT EXISTS "subscriptions" (
  "id"                     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"                UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "stripe_customer_id"     TEXT,
  "stripe_subscription_id" TEXT,
  "plan_id"                TEXT,
  "status"                 TEXT DEFAULT 'active',
  "current_period_start"   TIMESTAMPTZ,
  "current_period_end"     TIMESTAMPTZ,
  "created_at"             TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE "subscriptions" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "subscriptions_own_select" ON "subscriptions";
DROP POLICY IF EXISTS "subscriptions_own_insert" ON "subscriptions";
DROP POLICY IF EXISTS "subscriptions_own_update" ON "subscriptions";
CREATE POLICY "subscriptions_own_select" ON "subscriptions" FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "subscriptions_own_insert" ON "subscriptions" FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "subscriptions_own_update" ON "subscriptions" FOR UPDATE USING (user_id = auth.uid());

-- 9. REVIEW_REQUESTS (new table for tracking send requests)
CREATE TABLE IF NOT EXISTS "review_requests" (
  "id"             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"        UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "customer_name"  TEXT NOT NULL,
  "customer_email" TEXT,
  "customer_phone" TEXT,
  "channel"        TEXT DEFAULT 'email',
  "status"         TEXT DEFAULT 'pending',
  "sent_at"        TIMESTAMPTZ DEFAULT now(),
  "reviewed_at"    TIMESTAMPTZ,
  "created_at"     TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE "review_requests" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "review_requests_own_select" ON "review_requests";
DROP POLICY IF EXISTS "review_requests_own_insert" ON "review_requests";
DROP POLICY IF EXISTS "review_requests_own_update" ON "review_requests";
DROP POLICY IF EXISTS "review_requests_own_delete" ON "review_requests";
CREATE POLICY "review_requests_own_select" ON "review_requests" FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "review_requests_own_insert" ON "review_requests" FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "review_requests_own_update" ON "review_requests" FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "review_requests_own_delete" ON "review_requests" FOR DELETE USING (user_id = auth.uid());

-- 10. INDEXES
CREATE INDEX IF NOT EXISTS idx_reviews_user_id     ON "reviews" ("user_id");
CREATE INDEX IF NOT EXISTS idx_reviews_status      ON "reviews" ("status");
CREATE INDEX IF NOT EXISTS idx_contacts_user_id    ON "contacts" ("user_id");
CREATE INDEX IF NOT EXISTS idx_templates_user_id   ON "templates" ("user_id");
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON "notifications" ("user_id");
CREATE INDEX IF NOT EXISTS idx_notifications_read  ON "notifications" ("user_id", "read");
CREATE INDEX IF NOT EXISTS idx_team_members_user_id ON "team_members" ("user_id");
CREATE INDEX IF NOT EXISTS idx_subscriptions_user_id ON "subscriptions" ("user_id");
CREATE INDEX IF NOT EXISTS idx_review_requests_user_id ON "review_requests" ("user_id");

-- 11. AUTO-PROFILE TRIGGER (idempotent)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, business_name, plan)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data ->> 'full_name', NEW.email),
    '',
    'free'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();
