-- ============================
-- Migration 010: Dodo Payments
-- ============================

-- Add Dodo Payments columns to profiles
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "dodo_customer_id" TEXT;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "dodo_subscription_id" TEXT;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "subscription_status" TEXT DEFAULT 'inactive';
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "payment_status" TEXT DEFAULT 'none';
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "last_payment_at" TIMESTAMPTZ;

-- Dodo sessions tracking table
CREATE TABLE IF NOT EXISTS "dodo_sessions" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  "session_id" TEXT UNIQUE NOT NULL,
  "subscription_id" TEXT,
  "customer_id" TEXT,
  "plan" TEXT NOT NULL,
  "billing" TEXT NOT NULL,
  "status" TEXT DEFAULT 'pending',
  "created_at" TIMESTAMPTZ DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "dodo_sessions" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own dodo sessions" ON "dodo_sessions";
CREATE POLICY "Users can view their own dodo sessions"
  ON "dodo_sessions" FOR SELECT
  USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_dodo_sessions_user ON dodo_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_dodo_sessions_session ON dodo_sessions(session_id);
