-- ============================
-- Migration 011: Automations + Referrals
-- ============================

-- 1. AUTOMATIONS table
CREATE TABLE IF NOT EXISTS "automations" (
  "id"         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id"    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "name"       TEXT NOT NULL,
  "trigger"    TEXT DEFAULT 'After service ends',
  "delay"      TEXT DEFAULT '1 hour',
  "channel"    TEXT DEFAULT 'SMS' CHECK (channel IN ('SMS', 'Email', 'Both')),
  "active"     BOOLEAN DEFAULT TRUE,
  "sent_count" INTEGER DEFAULT 0,
  "created_at" TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "automations" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "automations_own_select" ON "automations";
DROP POLICY IF EXISTS "automations_own_insert" ON "automations";
DROP POLICY IF EXISTS "automations_own_update" ON "automations";
DROP POLICY IF EXISTS "automations_own_delete" ON "automations";
CREATE POLICY "automations_own_select" ON "automations" FOR SELECT USING (user_id = auth.uid());
CREATE POLICY "automations_own_insert" ON "automations" FOR INSERT WITH CHECK (user_id = auth.uid());
CREATE POLICY "automations_own_update" ON "automations" FOR UPDATE USING (user_id = auth.uid());
CREATE POLICY "automations_own_delete" ON "automations" FOR DELETE USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_automations_user ON automations(user_id);

-- 2. REFERRALS table
CREATE TABLE IF NOT EXISTS "referrals" (
  "id"             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "referrer_id"    UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  "referred_name"  TEXT,
  "referred_email" TEXT,
  "status"         TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'converted', 'expired')),
  "credit_earned"  INTEGER DEFAULT 0,
  "created_at"     TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE "referrals" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "referrals_own_select" ON "referrals";
DROP POLICY IF EXISTS "referrals_own_insert" ON "referrals";
DROP POLICY IF EXISTS "referrals_own_update" ON "referrals";
DROP POLICY IF EXISTS "referrals_own_delete" ON "referrals";
CREATE POLICY "referrals_own_select" ON "referrals" FOR SELECT USING (referrer_id = auth.uid());
CREATE POLICY "referrals_own_insert" ON "referrals" FOR INSERT WITH CHECK (referrer_id = auth.uid());
CREATE POLICY "referrals_own_update" ON "referrals" FOR UPDATE USING (referrer_id = auth.uid());
CREATE POLICY "referrals_own_delete" ON "referrals" FOR DELETE USING (referrer_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON referrals(referrer_id);

-- 3. REFERRAL CODE on profiles
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS referral_code TEXT UNIQUE;
CREATE INDEX IF NOT EXISTS idx_profiles_referral_code ON profiles(referral_code);

-- 4. WEBHOOK EVENTS table (idempotency for dodo-webhook)
CREATE TABLE IF NOT EXISTS webhook_events (
  "id"           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "event_id"     TEXT UNIQUE NOT NULL,
  "event_type"   TEXT NOT NULL,
  "processed_at" TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_webhook_events_event_id ON webhook_events(event_id);

-- 5. GRANT service role access
GRANT ALL ON automations TO service_role;
GRANT ALL ON referrals TO service_role;
GRANT ALL ON webhook_events TO service_role;
